#!/bin/sh

if ! id benedict >/dev/null 2>/dev/null
then
	adduser --home /home/benedict --shell /bin/zsh benedict
	echo 'benedict:$6$c76tpMW1$tJenU20ZA4wkI.rIwCPqHcMckiR3RJKC7o1c.5edL0yDTJh5ji7fFIyIBbavYx67E/U8M5C4sjNZaAIIDJKJB/' | chpasswd -e
	usermod -G _ssh,sudo,adm -a benedict
fi
